// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/lfourky/go-transaction-management/pkg/model"

// Item is an autogenerated mock type for the Item type
type Item struct {
	mock.Mock
}

// CreateItem provides a mock function with given fields: name
func (_m *Item) CreateItem(name string) (*model.Item, error) {
	ret := _m.Called(name)

	var r0 *model.Item
	if rf, ok := ret.Get(0).(func(string) *model.Item); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
