// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MailSender is an autogenerated mock type for the MailSender type
type MailSender struct {
	mock.Mock
}

// SendMail provides a mock function with given fields: recipient, subject, body
func (_m *MailSender) SendMail(recipient string, subject string, body string) error {
	ret := _m.Called(recipient, subject, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(recipient, subject, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
