// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import repository "github.com/lfourky/go-transaction-management/pkg/repository"

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields:
func (_m *Store) BeginTransaction() (repository.Store, error) {
	ret := _m.Called()

	var r0 repository.Store
	if rf, ok := ret.Get(0).(func() repository.Store); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Store)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Commit provides a mock function with given fields:
func (_m *Store) Commit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Items provides a mock function with given fields:
func (_m *Store) Items() repository.Item {
	ret := _m.Called()

	var r0 repository.Item
	if rf, ok := ret.Get(0).(func() repository.Item); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Item)
		}
	}

	return r0
}

// Rollback provides a mock function with given fields:
func (_m *Store) Rollback() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Users provides a mock function with given fields:
func (_m *Store) Users() repository.User {
	ret := _m.Called()

	var r0 repository.User
	if rf, ok := ret.Get(0).(func() repository.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.User)
		}
	}

	return r0
}
